DROP SEQUENCE TA_TAG_SEQ;
DROP TABLE TAG;

SELECT * FROM TAG ORDER BY IM_NO DESC;

CREATE SEQUENCE TA_TAG_SEQ;

CREATE TABLE TAG(
	IM_NO NUMBER NOT NULL,
	TA_LABELTAG VARCHAR2(100) NOT NULL,
	TA_TEXTTAG VARCHAR2(100),
	CONSTRAINT TAG_FK01 FOREIGN KEY(IM_NO) REFERENCES IMG(IM_NO)
);

ALTER TABLE TAG DROP CONSTRAINT TAG_UQ01;

SELECT TS_WRITER, TS_TITLE, IM_SERVERNAME, IM_FILEPATH
		FROM TATTOOSHARE
		JOIN IMG USING(IM_NO)
		WHERE IM_NO IN
		(SELECT IM_NO FROM TAG WHERE INSTR('Lion Flower', TA_LABELTAG) ;