DROP TABLE TATTOBO;
DROP TABLE NOTICEBO;
DROP TABLE REVIEWBO;
DROP TABLE NOTICEBOARD;

DROP SEQUENCE RE_NO_SEQ;
DROP TABLE REVIEW;

CREATE SEQUENCE RE_NO_SEQ;

CREATE TABLE REVIEW(
  RE_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  RE_WRITER VARCHAR2(500) NOT NULL,
  RE_TITLE VARCHAR2(2000) NOT NULL,
  RE_CONTENT VARCHAR2(4000) NOT NULL,
  RE_REGDATE DATE NOT NULL,
  RE_READCOUNT NUMBER NOT NULL,
  RE_GROUPNO NUMBER NOT NULL,
  RE_STEP NUMBER NOT NULL,
  IM_FILENAME VARCHAR2(100) NOT NULL,
  RE_TITLETAB  NUMBER NOT NULL,
  RE_DELFLAG VARCHAR2(2) NOT NULL,
  CONSTRAINT REVIEW_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER(ME_NO),
  CONSTRAINT REVIEW_FK02 FOREIGN KEY (IM_FILENAME) REFERENCES IMG(IM_FILENAME),
  CONSTRAINT REVIEW_CK01 CHECK(RE_DELFLAG IN('Y','N'))
  );


SELECT *
FROM REVIEW;

DROP SEQUENCE ME_NO;
DROP TABLE MEMBER;

CREATE SEQUENCE ME_NO_SEQ;

CREATE TABLE MEMBER(
ME_NO NUMBER PRIMARY KEY,
ME_EMAIL VARCHAR2(500) NOT NULL,
ME_PW VARCHAR2(500) NOT NULL,
ME_NAME VARCHAR2(500) NOT NULL,
ME_NIC VARCHAR2(500),
ME_BIRTH DATE NOT NULL,
ME_PHONE VARCHAR2(100) NOT NULL,
ME_ENABLED VARCHAR2(2) NOT NULL,
ME_ROLE VARCHAR2(20) NOT NULL,
ME_SNS_TYPE VARCHAR2(50),
ME_SNS_TOKEN VARCHAR2(500),
CONSTRAINT MEMBER_CK01 CHECK (ME_ENABLED IN ('Y','N')),
CONSTRAINT MEMBER_CK02 CHECK (ME_ROLE IN ('A','U','T')),
CONSTRAINT MEMBER_UQ UNIQUE (ME_EMAIL)
);
SELECT *
FROM MEMBER;

DROP SEQUENCE NO_NO_SEQ;
DROP TABLE NOTICE;
CREATE SEQUENCE NO_NO_SEQ;

CREATE TABLE NOTICE(
  NO_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  NO_WRITER VARCHAR2(500) NOT NULL,
  NO_TITLE VARCHAR2(100) NOT NULL,
  NO_CONTENT VARCHAR2(3000) NOT NULL,
  NO_REGDATE DATE NOT NULL,
  CONSTRAINT NOTICE_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO)
);


SELECT *
FROM NOTICE;

DROP TABLE SNS;

CREATE TABLE SNS(
  SN_TYPE VARCHAR2(100) NOT NULL,
  SN_ID VARCHAR2(500) NOT NULL,
  SN_TOKEN VARCHAR2(100) PRIMARY KEY
);

SELECT *
FROM SNS;

DROP SEQUENCE CA_NO_SEQ;
DROP TABLE CALENDAR;

CREATE SEQUENCE CA_NO_SEQ;

CREATE TABLE CALENDAR(
  CA_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  CA_TITLE VARCHAR2(100) NOT NULL,
  CA_CONTENT VARCHAR2(3000) NOT NULL,
  CA_REGDATE DATE NOT NULL,
  CONSTRAINT CALENDAR_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO)
);

SELECT *
FROM CALENDAR;

DROP SEQUENCE PR_NO_SEQ;
DROP TABLE PROFILE;

CREATE SEQUENCE PR_NO_SEQ;

CREATE TABLE PROFILE(
  PR_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  PR_FILENAME VARCHAR2(100),
  PR_FILEPATH VARCHAR2(100),
  PR_TIME VARCHAR2(100),
  PR_PRECAUTION VARCHAR2(2000),
  PR_CONTENT VARCHAR2(4000),
  CONSTRAINT PROFILE_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO)
);

SELECT *
FROM PROFILE;

DROP SEQUENCE TS_NO_SEQ;
DROP TABLE TATTOOSHARE;

CREATE SEQUENCE TS_NO_SEQ;

CREATE TABLE TATTOOSHARE(
  TS_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  TS_WRITER VARCHAR2(500) NOT NULL,
  TS_TITLE VARCHAR2(2000) NOT NULL,
  TS_CONTENT VARCHAR2(4000) NOT NULL,
  TS_REGDATE DATE NOT NULL,
  TS_READCOUNT NUMBER NOT NULL,
  TS_GROUPNO NUMBER NOT NULL,
  TS_STEP NUMBER NOT NULL,
  IM_FILENAME VARCHAR2(100) NOT NULL,
  TS_TITLETAB NUMBER NOT NULL,
  TS_DELFLAG  VARCHAR2(2) NOT NULL,
  CONSTRAINT TATTOOSHARE_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO),
  CONSTRAINT TATTOOSHARE_FK02 FOREIGN KEY (IM_FILENAME) REFERENCES IMG (IM_FILENAME),
  CONSTRAINT TATTOOSHARE_CK01 CHECK (TS_DELFLAG IN ('Y','N'))
  );

SELECT *
FROM TATTOOSHARE;

DROP TABLE IMG;

CREATE TABLE IMG(
  IM_FILENAME VARCHAR2(100) PRIMARY KEY,
  IM_FILEPATH VARCHAR2(100) NOT NULL,
  IM_REGDATE DATE,
  IM_SERDATE DATE,
  IM_TAG VARCHAR2(50) NOT NULL
  );

SELECT *
FROM IMG;

DROP SEQUENCE TI_NO_SEQ;
DROP TABLE TATTOOINFO;

CREATE SEQUENCE TI_NO_SEQ;

CREATE TABLE TATTOOINFO(
  TI_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  TI_WRITER VARCHAR2(500) NOT NULL,
  TI_CONTENT VARCHAR2(2000) NOT NULL,
  TI_NAME VARCHAR2(500) NOT NULL,
  TI_PAY NUMBER NOT NULL,
  TI_DATE DATE NOT NULL,
  TI_INFO VARCHAR2(2) CHECK(TI_INFO IN('Y','N')),
  TI_END VARCHAR2(2) CHECK(TI_END IN('Y','N')),
  TI_REVIEW VARCHAR2(2) CHECK(TI_REVIEW IN('Y','N')),
  CONSTRAINT TATTOOINFO_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO)
 );

SELECT *
FROM TATTOOINFO;
 


DROP SEQUENCE HI_NO_SEQ;
DROP TABLE HISPAY;

CREATE SEQUENCE HI_NO_SEQ;

CREATE TABLE HISPAY(
  HI_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  HI_PG VARCHAR2(20) NOT NULL,
  HI_METHOD VARCHAR2(20) NOT NULL,
  HI_PAY NUMBER NOT NULL,
  HI_NAME VARCHAR2(500) NOT NULL,
  HI_EMAIL VARCHAR2(500),
  HI_TEL NUMBER NOT NULL,
  HI_DATE DATE NOT NULL,
  HI_INFO VARCHAR2(2) CHECK(HI_INFO IN('Y','N')),
  CONSTRAINT HISPAY_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO)
);

SELECT *
FROM HISPAY;