DROP SEQUENCE RE_NO_SEQ;
DROP TABLE REVIEW;

CREATE SEQUENCE RE_NO_SEQ;

CREATE TABLE REVIEW(
  RE_NO NUMBER PRIMARY KEY,
  RE_WRITER VARCHAR2(500) NOT NULL,
  RE_TITLE VARCHAR2(2000) NOT NULL,
  RE_CONTENT VARCHAR2(4000) NOT NULL,
  RE_REGDATE DATE NOT NULL,
  RE_READCOUNT NUMBER NOT NULL,
  IM_FILENAME VARCHAR2(100) NOT NULL,
  RE_DELFLAG VARCHAR2(2) NOT NULL,

  CONSTRAINT REVIEW_CK01 CHECK(RE_DELFLAG IN('Y','N'))
  );