DROP SEQUENCE QA_NO_SEQ;
DROP SEQUENCE GR_NO_SEQ;
DROP TABLE QNA;

CREATE SEQUENCE QA_NO_SEQ;
CREATE SEQUENCE GR_NO_SEQ;
CREATE TABLE QNA(
	QA_NO NUMBER PRIMARY KEY,
	ME_NO NUMBER NOT NULL,
	QA_GROUPNO NUMBER NOT NULL,			-- 글 그룹
	QA_GROUPSEQ NUMBER NOT NULL,		-- 그룹 순서
	QA_TITLETAB NUMBER NOT NULL,		-- 답글 탭. 원본 : 0, 답글 : 1, 대댓글: 2
	QA_TITLE VARCHAR2(100) NOT NULL,
	QA_WRITER VARCHAR2(500) NOT NULL,
	QA_CONTENT VARCHAR2(3000) NOT NULL,
	QA_IMG VARCHAR2(1000),
	QA_READCOUNT NUMBER NOT NULL,
	QA_REGDATE DATE NOT NULL,
	QA_DELFLAG VARCHAR2(2) NOT NULL,
	QA_CATEGORY VARCHAR2(30) NOT NULL,
	CONSTRAINT QNA_CK01 CHECK(QA_DELFLAG IN('Y','N'))
);
