SELECT * FROM IMG ORDER BY IM_REGDATE DESC;

DROP SEQUENCE IM_NO_SEQ;
DROP TABLE IMG;

CREATE SEQUENCE IM_NO_SEQ;

CREATE TABLE IMG(
	IM_NO NUMBER PRIMARY KEY,
	ME_NO NUMBER NOT NULL,
	IM_FILENAME VARCHAR2(100) NOT NULL,
	IM_SERVERNAME VARCHAR2(100) NOT NULL,
	IM_FILEPATH VARCHAR2(1000) NOT NULL,
	IM_REGDATE DATE
);
	CONSTRAINT IMG_FK01 FOREIGN KEY(ME_NO) REFERENCES MEMBER(ME_NO)
);

INSERT INTO IMG
VALUES('sample2.png', '/BlackINK/img/', 
SYSDATE, SYSDATE, 'Tattoo,Arm,Temporary tattoo,Joing,Plant,Font,Flower,Drawing ', NULL);

INSERT INTO IMG
VALUES('sample1.png', '/BlackINK/img/', 
SYSDATE, SYSDATE, 'Tattoo,Shoulder,Arm,Cool,Flesh,Tattoo artist,Human,Muscle,Joint,Human body ', NULL);

--외래키 컬럼삭제
ALTER TABLE IMG DROP FOREIGN KEY(TA_LABELTAG, TA_TEXTTAG) REFERENCES TAG(TA_LABELTAG,TA_TEXTTAG); ;
ALTER TABLE IMG DROP COLUMN TA_LABELTAG; 

--컬럼추가 
ALTER TABLE IMG ADD IM_FILEPATH VARCHAR2(1000) NOT NULL; 

--컬럼 제약조건 추가 
ALTER TABLE IMG ADD CONSTRAINT IMG_UQ01 UNIQUE(TA_LABELTAG, TA_TEXTTAG);
ALTER TABLE IMG ADD FOREIGN KEY(TA_LABELTAG, TA_TEXTTAG) REFERENCES TAG(TA_LABELTAG,TA_TEXTTAG); 

SELECT *
FROM IMG;

SELECT *
FROM TATTOOSHARE;

SELECT *
FROM TAG;

SELECT * FROM PROFILE;

DELETE FROM IMG WHERE IM_NO < 200;
DELETE FROM TAG WHERE IM_NO < 200;
DELETE FROM TATTOOSHARE WHERE IM_NO < 200;

SELECT ME_NO, ME_NIC, PR_SHOPNAME, PR_OPEN, PR_CLOSE, PR_POST,
			   PR_ADR_MAIN, PR_ADR_D1, PR_ADR_D2, PR_CONTENT
		FROM PROFILE JOIN MEMBER USING(ME_NO)
		WHERE ME_NO = 1;






























