DROP SEQUENCE RE_NO_SEQ;
DROP TABLE REVIEW;

CREATE SEQUENCE RE_NO_SEQ;

CREATE TABLE REVIEW(
  RE_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  RE_WRITER VARCHAR2(500) NOT NULL,
  RE_TITLE VARCHAR2(2000) NOT NULL,
  RE_CONTENT VARCHAR2(4000) NOT NULL,
  RE_IMG VARCHAR2(2000) NOT NULL,
  RE_REGDATE DATE NOT NULL,
  RE_READCOUNT NUMBER NOT NULL,
  RE_GROUPNO NUMBER NOT NULL,
  RE_STEP NUMBER NOT NULL,
  IM_FILENAME VARCHAR2(100) NOT NULL,
  RE_TITLETAB  NUMBER NOT NULL,
  RE_DELFLAG VARCHAR2(2) NOT NULL,

  CONSTRAINT REVIEW_CK01 CHECK(RE_DELFLAG IN('Y','N'))
  );
  CONSTRAINT REVIEW_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER(ME_NO),
  CONSTRAINT REVIEW_FK02 FOREIGN KEY (IM_FILENAME) REFERENCES IMG(IM_FILENAME),
	-- 임시로 빼놓음
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이', '글제목', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이2', '글제목2', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이3', '글제목3', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이4', '글제목4', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이5', '글제목5', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이6', '글제목6', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이7', '글제목7', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이8', '글제목8', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이9', '글제목9', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이10', '글제목10', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');
INSERT INTO REVIEW
VALUES (RE_NO_SEQ.NEXTVAL, 1, '글쓴이11', '글제목11', '글내용', SYSDATE, 0, 1, 1, 'location.url', 0, 'N');

SELECT *
FROM REVIEW
ORDER BY RE_NO;
		
		