DROP SEQUENCE QA_NO_SEQ;
DROP SEQUENCE GR_NO_SEQ;
DROP TABLE QNA;

CREATE SEQUENCE QA_NO_SEQ;
CREATE SEQUENCE GR_NO_SEQ;
CREATE TABLE QNA(
	QA_NO NUMBER PRIMARY KEY,
	QA_GROUPNO NUMBER NOT NULL,
	QA_GROUPSEQ NUMBER NOT NULL,
	QA_TITLETAB NUMBER NOT NULL,
	QA_TITLE VARCHAR2(100) NOT NULL,
	QA_WRITER VARCHAR2(500) NOT NULL,
	QA_CONTENT VARCHAR2(3000) NOT NULL,
	QA_IMG VARCHAR2(1000),
	QA_READCOUNT NUMBER NOT NULL,
	QA_REGDATE DATE NOT NULL,
	QA_DELFLAG VARCHAR2(2) NOT NULL,
	CONSTRAINT QNA_CK01 CHECK(QA_DELFLAG IN('Y','N'))
);
ME_NO NUMBER NOT NULL,
CONSTRAINT QNA_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER(ME_NO),
-- 임시로 빼둠

INSERT INTO QNA
VALUES (QA_NO_SEQ.NEXTVAL, GR_NO_SEQ.NEXTVAL, 1, 0, '임시제목','임시글쓴이','임시내용',0,SYSDATE,'N');
INSERT INTO QNA
VALUES (QA_NO_SEQ.NEXTVAL, GR_NO_SEQ.NEXTVAL, 1, 0, '임시제목','임시글쓴이','임시내용',0,SYSDATE,'N');
INSERT INTO QNA
VALUES (QA_NO_SEQ.NEXTVAL, GR_NO_SEQ.NEXTVAL, 1, 0, '임시제목','임시글쓴이','임시내용',0,SYSDATE,'N');
INSERT INTO QNA
VALUES (QA_NO_SEQ.NEXTVAL, GR_NO_SEQ.NEXTVAL, 1, 0, '임시제목','임시글쓴이','임시내용',0,SYSDATE,'N');
INSERT INTO QNA
VALUES (QA_NO_SEQ.NEXTVAL, GR_NO_SEQ.NEXTVAL, 1, 0, '임시제목','임시글쓴이','임시내용',0,SYSDATE,'N');
INSERT INTO QNA
VALUES (QA_NO_SEQ.NEXTVAL, GR_NO_SEQ.NEXTVAL, 1, 0, '임시제목','임시글쓴이','임시내용',0,SYSDATE,'N');

SELECT *
FROM QNA
ORDER BY QA_NO DESC, QA_GROUPSEQ;