DROP SEQUENCE NO_NO_SEQ;
DROP TABLE NOTICE;
CREATE SEQUENCE NO_NO_SEQ;

CREATE TABLE NOTICE(
  NO_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  NO_WRITER VARCHAR2(500) NOT NULL,
  NO_TITLE VARCHAR2(100) NOT NULL,
  NO_CONTENT VARCHAR2(3000) NOT NULL,
  NO_VIEW NUMBER NOT NULL,
  NO_REGDATE DATE NOT NULL
 
);

 CONSTRAINT NOTICE_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO)
 -- 임시로 빼둠.

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '글쓴이', '글제목', '글내용', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '또 다른 글쓴이', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '또 다른 녀석', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '완전 다른 놈', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '이제 누굴까 난', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '아이디어 고갈', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '으웽뱅뱅이', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '넥슬라이스', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '냐하', '또다른 글제목', '글내용이시담', 0, SYSDATE);

INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '코딩너무좋아', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '코딩너무', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '무좋아', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '딩너아', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '코좋', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '딩아', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '이야호', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '호호호호', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '룰룰룰', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '아이고저런', '또다른 글제목', '글내용이시담', 0, SYSDATE);
INSERT INTO NOTICE
VALUES (NO_NO_SEQ.NEXTVAL, 0, '또안돼니', '또다른 글제목', '글내용이시담', 0, SYSDATE);

SELECT *
FROM NOTICE
ORDER BY NO_NO;


SELECT COUNT(*) FROM NOTICE;

