DROP SEQUENCE CA_NO_SEQ;
DROP TABLE CANVAS;

CREATE SEQUENCE CA_NO_SEQ;

CREATE TABLE CANVAS(
	
	CA_NO NUMBER PRIMARY KEY,
	ME_NO NUMBER NOT NULL,
	CA_FILENAME VARCHAR2(100) NOT NULL,
	CA_SERVERNAME VARCHAR2(100) NOT NULL,
	CA_FILEPATH VARCHAR2(1000) NOT NULL,
	CA_REGDATE DATE

);

select * from canvas;