SELECT * 
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'TATTOOSHARE' ;

SELECT * FROM MEMBER;
SELECT * FROM NOTICE;
SELECT * FROM IMG;
SELECT * FROM TATTOOSHARE;

DROP SEQUENCE TS_NO_SEQ;
DROP SEQUENCE TS_GROUPNO_SEQ;

DROP TABLE TATTOOSHARE;

CREATE SEQUENCE TS_NO_SEQ;
CREATE SEQUENCE TS_GROUPNO_SEQ;

CREATE TABLE TATTOOSHARE(
  TS_NO NUMBER PRIMARY KEY,
  ME_NO NUMBER NOT NULL,
  TS_WRITER VARCHAR2(500) NOT NULL,
  TS_TITLE VARCHAR2(2000) NOT NULL,
  TS_CONTENT VARCHAR2(4000) NOT NULL,
  TS_REGDATE DATE NOT NULL,
  TS_READCOUNT NUMBER NOT NULL,
  TS_GROUPNO NUMBER NOT NULL,
  TS_STEP NUMBER NOT NULL,
  IM_NO NUMBER NOT NULL,
  TS_TITLETAB NUMBER NOT NULL,
  TS_DELFLAG  VARCHAR2(2) NOT NULL,
  CONSTRAINT TATTOOSHARE_CK01 CHECK (TS_DELFLAG IN ('Y','N'))
  );
  CONSTRAINT TATTOOSHARE_FK01 FOREIGN KEY (ME_NO) REFERENCES MEMBER (ME_NO),
  CONSTRAINT TATTOOSHARE_FK02 FOREIGN KEY (IM_FILENAME) REFERENCES IMG (IM_FILENAME)
  );

--
INSERT INTO TATTOOSHARE
VALUES(TS_NO_SEQ.NEXTVAL, 0, '관리자', '테스트', '테스트ing', SYSDATE, 0,
TS_GROUPNO_SEQ.NEXTVAL, 1, 'sample1.png', 1, 'N');

SELECT TS_NO, ME_NO, TS_WRITER, TS_TITLE, TS_CONTENT, TS_REGDATE, TS_READCOUNT,
TS_GROUPNO, TS_STEP, IM_FILENAME, TS_TITLETAB, TS_DELFLAG
FROM TATTOOSHARE ORDER BY TS_REGDATE DESC;


--컬럼삭제 
ALTER TABLE TATTOOSHARE DROP COLUMN IM_FILENAME;
ALTER TABLE TATTOOSHARE DROP COLUMN ME_NO;


--컬럼추가 
ALTER TABLE TATTOOSHARE ADD ME_NO NUMBER NOT NULL;
ALTER TABLE TATTOOSHARE ADD IM_NO NUMBER NOT NULL;

--컬럼 제약조건 추가 
ALTER TABLE TATTOOSHARE ADD FOREIGN KEY(IM_NO) REFERENCES IMG(IM_NO); 
ALTER TABLE TATTOOSHARE ADD FOREIGN KEY(ME_NO) REFERENCES MEMBER(ME_NO); 

SELECT TS_NO, T.ME_NO, TS_WRITER, TS_TITLE, TS_CONTENT, TS_REGDATE, IM_NO, IM_SERVERNAME
		FROM TATTOOSHARE T JOIN IMG I USING(IM_NO)
		WHERE IM_NO = 7;
		
SELECT * FROM IMG;




































