DROP SEQUENCE TI_NO_SEQ
DROP TABLE TATTOOINFO

CREATE SEQUENCE TI_NO_SEQ
CREATE TABLE TATTOOINFO(
	TI_NO NUMBER PRIMARY KEY,
	ME_NO NUMBER NOT NULL,
	TI_TITLE VARCHAR2(100) NOT NULL,
	TI_CONTENT VARCHAR2(4000) NOT NULL,
	TI_TNO NUMBER NOT NULL,
	TI_PAY NUMBER NOT NULL,
	TI_DATE VARCHAR2(50) NOT NULL,
	TI_TIME VARCHAR2(50) NOT NULL,
	TI_STATE VARCHAR2(2) NOT NULL,
	TI_REGDATE DATE NOT NULL,
	CONSTRAINT ME_NO_FK FOREIGN KEY (ME_NO) REFERENCES MEMBER(ME_NO),
	CONSTRAINT TI_STATE_CK CHECK(TI_STATE IN('Y','N'))
);

select * from tattooinfo where ti_tno = 1 order by ti_date
SELECT * FROM hispay
SELECT * FROM member

INSERT INTO TATTOOINFO VALUES(TI_NO_SEQ.NEXTVAL,1,'테스트제목1','테스트내용1',
137,100000,'20201003','170000','N',SYSDATE)

SELECT TI_NO, T.ME_NO, M.ME_NAME, TI_TITLE, TI_CONTENT, TI_TNO, TI_PAY, TI_DATE, TI_TIME, TI_STATE, TI_REGDATE
		FROM (SELECT (ROW_NUMBER() OVER(PARTITION BY TI_DATE ORDER BY TI_TIME)) RN ,TI_NO, ME_NO, TI_TITLE, TI_CONTENT, TI_TNO, TI_PAY, TI_DATE, TI_TIME, TI_STATE, TI_REGDATE
		FROM TATTOOINFO WHERE TI_TNO = 1 AND TI_DATE LIKE '202009%') T
		INNER JOIN MEMBER M ON T.ME_NO = M.ME_NO
		WHERE RN BETWEEN 1 AND 3

SELECT * FROM TATTOOINFO
		WHERE TI_TNO = 1
		AND TO_NUMBER(TI_DATE) BETWEEN '20200923' AND '20200923'

SELECT TI_NO, T.ME_NO, M.ME_NAME, TI_TITLE, TI_CONTENT, TI_TNO, TI_PAY, TI_DATE, TI_TIME, TI_STATE, TI_REGDATE 
FROM TATTOOINFO T INNER JOIN MEMBER M ON T.ME_NO = M.ME_NO
WHERE TI_DATE = '20200930' AND TI_TNO = 1 ORDER BY TI_TIME

SELECT TI_NO, T.ME_NO, M.ME_NIC, TI_TITLE, TI_CONTENT, TI_TNO, TI_PAY, TI_DATE, TI_TIME, TI_STATE, TI_REGDATE 
      FROM TATTOOINFO T INNER JOIN MEMBER M ON T.TI_TNO = M.ME_NO WHERE T.ME_NO = 138
















		