DROP SEQUENCE HI_NO_SEQ;
DROP TABLE HISPAY;

CREATE SEQUENCE HI_NO_SEQ;

CREATE TABLE HISPAY(

	TI_NO NUMBER PRIMARY KEY,
	ME_NO NUMBER NOT NULL,
	HI_NO VARCHAR2(25) NOT NULL,
	HI_METHOD VARCHAR2(20) NOT NULL,
	TI_PAY NUMBER NOT NULL,
	HI_PAY NUMBER NOT NULL,
	TI_TITLE VARCHAR2(500) NOT NULL,
	HI_EMAIL VARCHAR2(500) NOT NULL,
	HI_BNAME VARCHAR2(100),
	HI_BNUM VARCHAR2(100),
	HI_BDATE DATE,
	HI_DATE DATE NOT NULL,
	HI_STATE VARCHAR2(2) NOT NULL,
	
--	FOREIGN KEY(TI_NO) REFERENCES TATTOOINFO(TI_NO),
	CONSTRAINT HISPAY_CK01 CHECK (HI_STATE IN ('Y','N'))

);

-- 컬럼 수 : 14

SELECT * FROM HISPAY ORDER BY TI_NO;

